using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum BlockShape
{
    EMPTY,
    FULL,
    INSIDE,

    BACK,
    FRONT,
    LEFT,
    RIGHT,
    BOTTOM,
    TOP,

    DIAGONAL_BACK,
    DIAGONAL_FRONT,
    DIAGONAL_LEFT,
    DIAGONAL_RIGHT,

    SLOPE_BACK,
    SLOPE_FRONT,
    SLOPE_LEFT,
    SLOPE_RIGHT,

    SLOPE_BACK_INV,
    SLOPE_FRONT_INV,
    SLOPE_LEFT_INV,
    SLOPE_RIGHT_INV,

    CORNER_BACK_LEFT,
    CORNER_BACK_RIGHT,
    CORNER_FRONT_LEFT,
    CORNER_FRONT_RIGHT,

    CORNER_BACK_LEFT_INV,
    CORNER_BACK_RIGHT_INV,
    CORNER_FRONT_LEFT_INV,
    CORNER_FRONT_RIGHT_INV,

    CORNER_BACK_LEFT_CONCAVE,
    CORNER_BACK_RIGHT_CONCAVE,
    CORNER_FRONT_LEFT_CONCAVE,
    CORNER_FRONT_RIGHT_CONCAVE,

    CORNER_BACK_LEFT_CONCAVE_INV,
    CORNER_BACK_RIGHT_CONCAVE_INV,
    CORNER_FRONT_LEFT_CONCAVE_INV,
    CORNER_FRONT_RIGHT_CONCAVE_INV,
}